# Generated by Django 3.2.3 on 2021-05-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Book Title ')),
                ('author', models.CharField(max_length=128)),
                ('price', models.FloatField(verbose_name='Book Price')),
                ('description', models.CharField(max_length=256)),
                ('long_description', models.TextField()),
            ],
        ),
    ]
