# Generated by Django 3.2.3 on 2021-05-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.CharField(max_length=256, null=True, verbose_name='Book Image'),
        ),
    ]
