# Generated by Django 3.1.5 on 2021-05-20 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_review_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
    ]
